// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/memory.proto

package openbrain_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Records       []*MemoryRecord        `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *IngestRequest) GetRecords() []*MemoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type IngestResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordsIngested int32                  `protobuf:"varint,1,opt,name=records_ingested,json=recordsIngested,proto3" json:"records_ingested,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetRecordsIngested() int32 {
	if x != nil {
		return x.RecordsIngested
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*MemoryRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetRecords() []*MemoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type ForgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	RecordIds     []string               `protobuf:"bytes,2,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetRequest) Reset() {
	*x = ForgetRequest{}
	mi := &file_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetRequest) ProtoMessage() {}

func (x *ForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetRequest.ProtoReflect.Descriptor instead.
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *ForgetRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ForgetRequest) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

type ForgetResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecordsForgotten int32                  `protobuf:"varint,1,opt,name=records_forgotten,json=recordsForgotten,proto3" json:"records_forgotten,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForgetResponse) Reset() {
	*x = ForgetResponse{}
	mi := &file_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetResponse) ProtoMessage() {}

func (x *ForgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetResponse.ProtoReflect.Descriptor instead.
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *ForgetResponse) GetRecordsForgotten() int32 {
	if x != nil {
		return x.RecordsForgotten
	}
	return 0
}

type MemoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRecord) Reset() {
	*x = MemoryRecord{}
	mi := &file_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecord) ProtoMessage() {}

func (x *MemoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecord.ProtoReflect.Descriptor instead.
func (*MemoryRecord) Descriptor() ([]byte, []int) {
	return file_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryRecord) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MemoryRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_v1_memory_proto protoreflect.FileDescriptor

const file_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/memory.proto\x12\fopenbrain.v1\"h\n" +
	"\rIngestRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x124\n" +
	"\arecords\x18\x02 \x03(\v2\x1a.openbrain.v1.MemoryRecordR\arecords\";\n" +
	"\x0eIngestResponse\x12)\n" +
	"\x10records_ingested\x18\x01 \x01(\x05R\x0frecordsIngested\"]\n" +
	"\fQueryRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"E\n" +
	"\rQueryResponse\x124\n" +
	"\arecords\x18\x01 \x03(\v2\x1a.openbrain.v1.MemoryRecordR\arecords\"Q\n" +
	"\rForgetRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1d\n" +
	"\n" +
	"record_ids\x18\x02 \x03(\tR\trecordIds\"=\n" +
	"\x0eForgetResponse\x12+\n" +
	"\x11records_forgotten\x18\x01 \x01(\x05R\x10recordsForgotten\"\xb5\x01\n" +
	"\fMemoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.openbrain.v1.MemoryRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdb\x01\n" +
	"\rMemoryService\x12C\n" +
	"\x06Ingest\x12\x1b.openbrain.v1.IngestRequest\x1a\x1c.openbrain.v1.IngestResponse\x12@\n" +
	"\x05Query\x12\x1a.openbrain.v1.QueryRequest\x1a\x1b.openbrain.v1.QueryResponse\x12C\n" +
	"\x06Forget\x12\x1b.openbrain.v1.ForgetRequest\x1a\x1c.openbrain.v1.ForgetResponseB>Z<github.com/chifamba/vashandi/openbrain/proto/v1;openbrain_v1b\x06proto3"

var (
	file_v1_memory_proto_rawDescOnce sync.Once
	file_v1_memory_proto_rawDescData []byte
)

func file_v1_memory_proto_rawDescGZIP() []byte {
	file_v1_memory_proto_rawDescOnce.Do(func() {
		file_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_memory_proto_rawDesc), len(file_v1_memory_proto_rawDesc)))
	})
	return file_v1_memory_proto_rawDescData
}

var file_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_memory_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: openbrain.v1.IngestRequest
	(*IngestResponse)(nil), // 1: openbrain.v1.IngestResponse
	(*QueryRequest)(nil),   // 2: openbrain.v1.QueryRequest
	(*QueryResponse)(nil),  // 3: openbrain.v1.QueryResponse
	(*ForgetRequest)(nil),  // 4: openbrain.v1.ForgetRequest
	(*ForgetResponse)(nil), // 5: openbrain.v1.ForgetResponse
	(*MemoryRecord)(nil),   // 6: openbrain.v1.MemoryRecord
	nil,                    // 7: openbrain.v1.MemoryRecord.MetadataEntry
}
var file_v1_memory_proto_depIdxs = []int32{
	6, // 0: openbrain.v1.IngestRequest.records:type_name -> openbrain.v1.MemoryRecord
	6, // 1: openbrain.v1.QueryResponse.records:type_name -> openbrain.v1.MemoryRecord
	7, // 2: openbrain.v1.MemoryRecord.metadata:type_name -> openbrain.v1.MemoryRecord.MetadataEntry
	0, // 3: openbrain.v1.MemoryService.Ingest:input_type -> openbrain.v1.IngestRequest
	2, // 4: openbrain.v1.MemoryService.Query:input_type -> openbrain.v1.QueryRequest
	4, // 5: openbrain.v1.MemoryService.Forget:input_type -> openbrain.v1.ForgetRequest
	1, // 6: openbrain.v1.MemoryService.Ingest:output_type -> openbrain.v1.IngestResponse
	3, // 7: openbrain.v1.MemoryService.Query:output_type -> openbrain.v1.QueryResponse
	5, // 8: openbrain.v1.MemoryService.Forget:output_type -> openbrain.v1.ForgetResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_memory_proto_init() }
func file_v1_memory_proto_init() {
	if File_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_memory_proto_rawDesc), len(file_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_memory_proto_goTypes,
		DependencyIndexes: file_v1_memory_proto_depIdxs,
		MessageInfos:      file_v1_memory_proto_msgTypes,
	}.Build()
	File_v1_memory_proto = out.File
	file_v1_memory_proto_goTypes = nil
	file_v1_memory_proto_depIdxs = nil
}
