package db

import (
	"github.com/chifamba/vashandi/vashandi/backend/db/models"
	"gorm.io/gorm"
)

// RunMigrations applies GORM AutoMigrate to all models in the models package.
func RunMigrations(db *gorm.DB) error {
	// We use the search_path provided in the DSN to target the correct schema.
	return db.AutoMigrate(
		&models.Company{},
		&models.CompanyLogo{},
		&models.CompanyMembership{},
		&models.User{},
		&models.Session{},
		&models.Account{},
		&models.Verification{},
		&models.InstanceSetting{},
		&models.InstanceUserRole{},
		&models.BudgetPolicy{},
		&models.BudgetIncident{},
		&models.Project{},
		&models.Goal{},
		&models.ProjectGoal{},
		&models.Issue{},
		&models.IssueComment{},
		&models.IssueAttachment{},
		&models.IssueLabel{},
		&models.Label{},
		&models.IssueRelation{},
		&models.IssueExecutionDecision{},
		&models.IssueApproval{},
		&models.Approval{},
		&models.ApprovalComment{},
		&models.IssueReadState{},
		&models.IssueInboxArchive{},
		&models.InboxDismissal{},
		&models.Agent{},
		&models.AgentAPIKey{},
		&models.AgentConfigRevision{},
		&models.AgentRuntimeState{},
		&models.AgentTaskSession{},
		&models.AgentWakeupRequest{},
		&models.WorkspaceRuntimeService{},
		&models.WorkspaceOperation{},
		&models.ExecutionWorkspace{},
		&models.ProjectWorkspace{},
		&models.ActivityLog{},
		&models.Asset{},
		&models.CostEvent{},
		&models.FinanceEvent{},
		&models.Document{},
		&models.DocumentRevision{},
		&models.IssueDocument{},
		&models.IssueWorkProduct{},
		&models.Plugin{},
		&models.PluginConfig{},
		&models.PluginJob{},
		&models.PluginJobRun{},
		&models.PluginEntity{},
		&models.PluginState{},
		&models.PluginWebhookDelivery{},
		&models.PluginLog{},
		&models.Routine{},
		&models.RoutineRun{},
		&models.RoutineTrigger{},
		&models.HeartbeatRun{},
		&models.HeartbeatRunEvent{},
		&models.Invite{},
		&models.JoinRequest{},
		&models.BoardAPIKey{},
		&models.PrincipalPermissionGrant{},
		&models.FeedbackExport{},
		&models.FeedbackVote{},
	)
}
